### ISSUE TITLE
Can’t access challenges

### ISSUE THREAD

**Issue by Brikaa** [engineer-man/emkc#96]
Trying to access the challenges locally gives this:
```
(node:77) UnhandledPromiseRejectionWarning: SequelizeDatabaseError: Expression #7 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'emkc.solution.user_challenge_id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
    at Query.formatError (/opt/emkc/platform/node_modules/sequelize/lib/dialects/mysql/query.js:239:16)
    at Query.run (/opt/emkc/platform/node_modules/sequelize/lib/dialects/mysql/query.js:54:18)
    at async /opt/emkc/platform/node_modules/sequelize/lib/sequelize.js:619:16
(node:77) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

**Comment by realtux** [comment]
check var/docker/config/mysqld.cnf and make sure `sql_mode = ""` is in there. perhaps you haven't pulled lately?

**Comment by Brikaa** [comment]
> check var/docker/config/mysqld.cnf and make sure `sql_mode = ""` is in there. perhaps you haven't pulled lately?

I’ll check that. Maybe we can set the sql_mode on startup from the docker-compose file?

**Comment by realtux** [comment]
that should already be happening because that folder and file are mounted on top of the config for the container, re: https://github.com/engineer-man/emkc/blob/develop/docker-compose.yml#L34

**Comment by Brikaa** [comment]
Solved by making mysqld.cnf read-only since MySQL was ignoring it for being a "world-writable" file.
